### PR TITLE
LanguageIdentifier.swift

### PR DESCRIPTION
**Pull request by johnno1962**
Add Swift as language identifier!

### CODE REVIEW

**Comment by mattmassicotte** [comment]
Yes!

Thank you so much for this change. It's very appreciated!

**Comment by johnno1962** [comment]
Thanks Matt. I’ve been working with this library (the example in the README.md was a big help) but been unable to convince sourcekit-lsp to use the index db to implement “references”. Any advice?

**Comment by mattmassicotte** [comment]
I'm so glad to hear it's working for you! I tried out sourcekit-lsp for about 30 seconds a lot time ago, but haven't touched it since.

I'm afraid I'm not at all familiar with the sourcekit-lsp's index db. Perhaps it's controlled by an initialization option and/or command line option? Lots of language servers use those.

**Comment by johnno1962** [comment]
Thanks for very much for this library. It’s been very easy to work with. Finally, after a lot of frigging about I found the solution. You need to pass the PATH through to the `LanguageServerProcessHost`:
```
let host = LanguageServerProcessHost(path: executablePath, arguments: [], environment: ["PATH": "/usr/bin"])
```
Others you get an error:
```
failed to create SwiftPMWorkspace: could not find executable for ‘xcrun’
```
and it doesn’t pick up the index.

**Comment by mattmassicotte** [comment]
Ahhh, yes! Capturing the right environment for your language server is critical! I have similar problems. That's exactly what the `environment` argument is for. You might find that there are other variables needed too. The various Go servers I've used need a lot of configuration in this area.

**Comment by mattmassicotte** [comment]
Looking forward to seeing your project!

**Pull request merged**
