### PR TITLE
Support for 'prepareRename' and 'rename'.

### PR DESCRIPTION
**Pull request by alidn**
Hi, thank you for this package.

This pull-request adds support for 'prepareRename' and 'rename' features. I wanted to add documentation too, but wanted to stay consistent with the rest of the package; if it's okay I can gradually add doc for most features as I use them.

### CODE REVIEW

**Comment by mattmassicotte** [comment]
I'm so happy you've found it useful, and thank you so much for this contribution!

I'm glad you were able to find a way to add what you needed. I've had a hard time managing all of the types required, and have experimented with a few different approaches in this library. It can make it messy at times, but it looks like what you added is great!

**Comment by mattmassicotte** [comment]
@alidn just a ping to let you know that CI failed for this PR. Looks like a configuration issue.

**Comment by alidn** [comment]
I'm sorry Matt, I honestly don't know how to fix the CI issues, can you please point me to the right place so I can fix it.

> I'm glad you were able to find a way to add what you needed. I've had a hard time managing all of the types required, and have experimented with a few different approaches in this library. 

Thank you! IMO it's a lot easier to use and contribute to than the equivalent Rust library I previously used.

**Comment by alidn** [comment]
Hi again, I think I finally fixed the problem. I had opened the folder in Xcode rather than the `.xcodeproj` file 🤦

**Comment by mattmassicotte** [comment]
Thanks so much for your work on this!

**Pull request merged**
