### PR TITLE
More locking in ProtocolTransport to try to resolve 'not matching res…

### PR DESCRIPTION
**Pull request by johnno1962**
…ponder for numericId(4564) in [:], dropping message'

### CODE REVIEW

**Comment by johnno1962** [comment]
Hi @mattmassicotte, Using the instructions in https://github.com/ChimeHQ/SwiftLSPClient/pull/28 I've been able to improve reliability by introducing code to synchronise access to `ProtocolTransport.responsers`. The situation is much improved but it is still possible to get a message `not matching responder for..` though it is much rarer now. I don't really know what the problem is myself. Perhaps it is upstream?

**Comment by johnno1962** [comment]
In fact, this problem seems to be fixed with these locks.

**Comment by mattmassicotte** [comment]
Given we now understand the issue, I'm afraid locks cannot guarantee this will work. The locking is just changing the timing, which is helping you win the race more frequently :(

**Comment by johnno1962** [comment]
In fact I have seen one instance of a failure with these locks in place. It seemed to be the lock on generateID that had the most effect though I can't be sure.

**Comment by mattmassicotte** [comment]
Yeah, not surprised. The locks are just influencing timing, not actually providing a guarantee of the order of operations you need :(

**Comment by johnno1962** [comment]
But, but, but the stress tester works now. It's doing 6000 requests per iteration. I'd recommend merging this as it does no harm and this is likely a once in a blue moon failure mode for the lib.

**Comment by mattmassicotte** [comment]
Ok I'm glad it's working for you. However, this change actually is problematic.

You've introduced a `DispatchQueue.global().asyncAfter`. That is giving the main runloop a chance to receive and process the response from the server over the FileHandle connection. But, this hasn't actually fixed the issue. It just made it much less likely. How did you determine 2 seconds is enough time? Though rare, I have absolutely seen LSP response latencies longer than that.

And now, `dispatchMessage` can get into an infinite loop.

I'm afraid your code is gonna need to use of block callbacks in a few more places. But, fundamentally, you are interacting with asynchronous systems with LSP and SourceKit. Callbacks like this are super common throughout Foundation and AppKit anyway. And, doing this will actually guarantee correct behavior.

I don't want to make more work for you. But, I also like to make sure that this really gets fixed.

**Comment by johnno1962** [comment]
The `DispatchQueue.global().asyncAfter` was a try at recovering from a missing numericId and didn’t work anyway so it’s a bit of a red herring. I’ll leave this open as I’m convinced it makes positive difference in the reliability of the library synchronous or asynchronous. You can close it if you like and I’ll maintain my own fork.

**Comment by mattmassicotte** [comment]
So, with no delay, this fixes your issue? That’s interesting!

I’ve never seen a crash in my app in this area. Would you be willing to share a crash report with me?

**Comment by johnno1962** [comment]
I would, but there is no crash report. The application hangs with the error message `not matching responder for numericId(5876) in [:], dropping message`. The easiest way for you to replicate this is to clone the app and change Package.swift to use your fork of the lib. 
````
$ git clone https://github.com/johnno1962/siteify -b port-to-lsp
$ cd siteify
$ swift build
$ open siteify.xcodeproj
# build Xcode project
$ .build/debug/siteify
```
Unfortunately using this configuration I’m unable to replicate the crash at the moment. I don’t know what’s changed but it is a race condition for sure related to timing. I’ll let you know if it crops up again. Looks good at the moment.

**Comment by mattmassicotte** [comment]
Ok, so this crash makes perfect sense to me. It is being caused by your use of SwiftLSPClient on more than one thread. I've updated the documentation for `LanguageServerProcessHost` to be clear that this isn't supported.

Unfortunately NSFileHandle **cannot** be made to work correctly with only locks. It's a runloop-based API, and **must** "live" for lack of a better word, on a single thread. Usually that's the main thread, but it does not need to be.

Can I ask why you aren't able to use callbacks in your application?

Alternatively, would you consider making a single-threaded wrapper around SwiftLSPClient for your application? I haven't thought deeply about this, but it should completely solve the issue for you, and will not require library level changes.

**Comment by mattmassicotte** [comment]
And, just so you know, I'm not just trying to be a pain. I really am also trying to think of ways to achieve what you want. NSFileHandle is really hard to use in this respect. Some of the few APIs that was never migrated off of runloop concurrency model. And, because it's tied directly to how NSTask works, it's tough to replace.

**Comment by mattmassicotte** [comment]
Ok - progress! I have been reading the docs on NSFileHandle, and I was incorrect that it can only work with runloops, which is fantastic news. I think we can fix this in a way that won't have any downsides. Investigating now.

**Comment by johnno1962** [comment]
Sound good! Sorry to  drive you so hard on this but I’m convinced one solution is to synchronise access to `ProtocolTransport.responders`. The crash dump is very informative. There is no runloop - this is not a Cocoa application only has a main thread. It seems when dataHandlers are used on an NSFileHandle it starts it’s own thread to run something like a select() to asynchronously detect data arriving which can interrupt whatever thread you are running at any time. As the application’s work thread can be starting a request at the same time a response arrives this can result in two threads making mutable accesses to `ProtocolTransport.responders` which is the only really mutable state once the connection to the lap executable has been set up data and mayhem ensues - either the rare crash or the `responders.removeValue(forKey: message.id)` resets the dictionary zapping the newly recorded `message.id` causing the responder not to be found. After a few iterations I’m happy with this PR now and been thrashing it all day - no crashes.

**Comment by mattmassicotte** [comment]
You have nothing at all to apologize for! This is my fault. A combination of misunderstanding and confusion because of that "not matching responder for" message. Mostly, I'm just an idiot. You've been incredibly patient and I'm so happy you continued to push on this.

Everything kind of makes sense how that I know `NSFileHandle` actually no longer uses run-loops exclusively. In hindsight this was obvious....

It's lucky you found a case that hits this problem with `ProtocolTransport`, but we actually need to have a closer look at `StdioDataTransport`, `ProtocolTransport` and `MessageTransport`. They are all stateful and all need proper synchronization.

I suspect the reason I've never hit this is the volume of LSP calls you make in your process is both very high and also in a tight loop. My app mostly operates at user-speed, so just never does this. But definitely could.

Please hang tight for now. I'm going to poke around and will update tomorrow. This PR does address a small part of the problem, but we'll need something a little bigger in scope.

**Comment by johnno1962** [comment]
This has been resolved by @mattmassicotte https://github.com/ChimeHQ/SwiftLSPClient/pull/30

**Pull request closed without merging**
